accounts/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.urls import include, path, reverse_lazy
from django.contrib.auth import views as auth_views
from accounts import views as accounts_views


app_name='accounts'

urlpatterns = [
    path('', accounts_views.AccountHomeView.as_view(), name='home'),
    path('activate/<uidb64>/<token>/', accounts_views.activate, name='activate'),
    path('bye/', accounts_views.logout_farewell, name='farewell'),
    path('contact/', accounts_views.send_email, name='send_email'),
    path('contact2/', accounts_views.send_email2, name='send_email2'),
    path('contact/sent/', accounts_views.thanks, name='thanks'),
    path('email_to_outbox/', accounts_views.email_to_outbox, name='email_to_outbox'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', accounts_views.signup, name='signup'),
    # path('signout/', accounts_views.signout, name='signout'), # bez ostrzezenia
    path('delete/', accounts_views.UserSignoutView.as_view(), name='delete'), ## deaktywuje, nie usuwa
    path('reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html',
                                                        email_template_name='accounts/password_reset_email.html',
                                                        subject_template_name='accounts/password_reset_subject.txt',
                                                        success_url=reverse_lazy('accounts:password_reset_done')
                                                        ), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
                                                        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
                                                        template_name='accounts/password_reset_confirm.html',
                                                        success_url=reverse_lazy('accounts:password_reset_complete')
                                                        ), name='password_reset_confirm'),
    path('reset/complete/', auth_views.PasswordResetCompleteView.as_view(
                                                        template_name='accounts/password_reset_complete.html'),
                                                        name='password_reset_complete'),
    path('update/', accounts_views.UserDetailUpdateView.as_view(), name='user-update'),
]

# path('resend-activation/', accounts_views.AccountEmailActivateView.as_view(), name='resend-activation'),

digitalmarket/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import include, path
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

import products.views
from products.views import UserLibraryListView
import tags.views
import dashboard.views
from dashboard.views import DashboardView
import checkout.views
from checkout.views import CheckoutTestView, CheckoutAjaxView
import sellers.views
from accounts import views as accounts_views

from django.conf.urls import include, url

from django.views.generic import TemplateView

from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

# Debug Toolbar: 
if settings.DEBUG:
    import debug_toolbar


urlpatterns = [
    path('kwakwa/', admin.site.urls, name='admin'),
    # https://docs.djangoproject.com/en/2.1/ref/contrib/admin/#hooking-adminsite-to-urlconf
    path('accounts/', include('accounts.urls')),
    path('', dashboard.views.DashboardView.as_view(), name='dashboard'),
    path('404', products.views.index, name='index'),
    path('checkout/', checkout.views.CheckoutAjaxView.as_view(), name='checkout'),
    path('library/', products.views.UserLibraryListView.as_view(), name='library'),
    path('products/', include('products.urls', namespace='products')),
    path('seller/', include('sellers.urls', namespace='sellers')),
    path('tags/', include('tags.urls', namespace='tags')),
    path('test/', checkout.views.CheckoutTestView.as_view(), name='test'),
]

handler404 = 'products.views.error_404_view'

urlpatterns += [
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico'), ), name="favicon" ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
    urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls)),]

if not settings.DEBUG:
    urlpatterns += [
        path('anymail/', include('anymail.urls')),  ## for sendgrid webhooks  # production only
    ]

tags/urls.py
from django.conf import settings
from django.conf.urls import url  #include, 
from django.conf.urls.static import static
from django.urls import include, path 
from . import views 
from .views import TagDetailView, TagListView 


app_name="tags"

urlpatterns = [
    path('', TagListView.as_view(), name='list'),   # tag_list.html
    path('<int:pk>/', TagDetailView.as_view(), name='detail'),  # tag_detail.html
    path('<slug>/', TagDetailView.as_view(), name='detail_slug'),  # tag_detail.html
] 

accounts/forms.py
from django import forms
#from verified_email_field.forms import VerifiedEmailField

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User



# https://medium.com/@frfahim/django-registration-with-confirmation-email-bb5da011e4ef
class SignUpForm(UserCreationForm):
    email = forms.CharField(max_length=254, required=True, widget=forms.EmailInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')




# our new form
class ContactForm(forms.Form):
    subject= forms.CharField(required=True)
    from_email = forms.EmailField(required=True)
    form_content = forms.CharField(
        required=True,
        widget=forms.Textarea
    )

    # the new bit we're adding
    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['subject'].label = "Subject:"
        self.fields['from_email'].label = "Your email:"
        self.fields['form_content'].label = "What do you want to say?"



class UserDetailChangeForm(forms.ModelForm):
    full_name = forms.CharField(label='Name', required=False, widget=forms.TextInput(attrs={"class": 'form-control'}))

    class Meta:
        model = User
        fields = ['username']

accounts/views.py
import datetime

from django.conf import settings
from django.contrib.auth import login as auth_login
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from .forms import SignUpForm, ContactForm, UserDetailChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import UpdateView, DetailView
from django.views.generic.edit import UpdateView as UpdateView_edit

from django.core.mail import send_mail
from django.core.mail import EmailMessage
from django.shortcuts import redirect
from django.template.loader import get_template
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.core.mail import BadHeaderError

from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage


from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from sellers.models import SellerAccount
from products.models import Product



# when more than one emal backend:
import os
from decouple import config
from django.core.mail.backends.base import BaseEmailBackend
from django.conf import settings
from django.core.mail import send_mail, get_connection
from django.core.mail import (
    EmailMessage, EmailMultiAlternatives, mail_admins, mail_managers,
    send_mail, send_mass_mail,
    )

from digitalmarket import settings

EMAIL_FILE_PATH = os.path.join(settings.BASE_DIR, "emails_file")
FILE_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
# WORKING_EMAIL_BACKEND = config('EMAIL_BACKEND')
# EMAIL_BACKEND_LIST = [WORKING_EMAIL_BACKEND, FILE_BACKEND]







# https://medium.com/@frfahim/django-registration-with-confirmation-email-bb5da011e4ef
def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your account.'
            message = render_to_string('acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                # 'uid':urlsafe_base64_encode(force_bytes(user.pk)),  # older django
                'uid':urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token':account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')
    else:
        form = SignUpForm()
    return render(request, 'accounts/signup.html', {'form': form})







# https://medium.com/@frfahim/django-registration-with-confirmation-email-bb5da011e4ef
def activate(request, uidb64, token):
    success_url = reverse_lazy('my_account')
#    success_url = reverse_lazy('sellers:dashboard')

    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        seller = SellerAccount.objects.create(user=user)
        seller.active = True
        seller.save()
        if settings.DEBUG:
            print(seller, seller.active)
        auth_login(request, user)
        return redirect('accounts:login')
#        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')



# mitch 2019-06
class AccountHomeView(LoginRequiredMixin, DetailView):
    template_name = 'accounts/home.html'
    def get_object(self):
        return self.request.user



# mitch 2019-06
class UserDetailUpdateView(LoginRequiredMixin, UpdateView):
    form_class = UserDetailChangeForm
    template_name = 'accounts/detail-update-view.html'

    def get_object(self):
        return self.request.user

    def get_context_data(self, *args, **kwargs):
        context = super(UserDetailUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Update'
        return context

    def get_success_url(self):
        return reverse("accounts:home")




# from django.views.decorators.debug import sensitive_variables
# from django.views.decorators.debug import sensitive_post_parameters
# @sensitive_variables('password', 'email')
# @sensitive_post_parameters('password', 'email')
# @method_decorator(login_required, name='dispatch')



########## TODO -- https://docs.djangoproject.com/en/2.2/howto/error-reporting/
# from django.views.decorators.debug import sensitive_post_parameters
#
# @sensitive_post_parameters('pass_word', 'credit_card_number')
# def record_user_profile(request):
#     UserProfile.create(
#         user=request.user,
#         password=request.POST['pass_word'],
#         credit_card=request.POST['credit_card_number'],
#         name=request.POST['name'],
#     )
#



def logout_farewell(request):
    template='accounts/farewell.html'
    return render(request, template, {})



#------------------------------------



### emails sent by user to FILE:
# w settings.py musi byc:
# # File Email Backend
# EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
# EMAIL_FILE_PATH = os.path.join(BASE_DIR, "emails_file")

# https://wsvincent.com/django-user-authentication-tutorial-password-reset/

# najwazniejsze za:
# https://hellowebbooks.com/news/tutorial-setting-up-a-contact-form-with-django/

# def send_email(request):
#     form_class = ContactForm

#     if request.method == 'POST':
#         form = form_class(data=request.POST)

#         if form.is_valid():
#             subject = request.POST.get('subject', '')
#             from_email = request.POST.get('from_email', '')
#             form_content = request.POST.get('form_content', '')
#             template = get_template('contact/contact_template.txt')

#             context = {
#                 'subject': subject,
#                 'from_email': from_email,
#                 'form_content': form_content,
#             }

#             content = template.render(context)
#             print(context, '')

#             email = EmailMessage(
#                 subject,
#                 'Our customer wrote: \n`'+form_content+'`',
#                 "live-pages.live website  " +str(request.user),
#                 [settings.DEFAULT_FROM_EMAIL],
#                 headers = {'Reply-To': from_email, }
#             )
#             # email.send()
#             try:
#                 email.send()
#             except BadHeaderError:
#                 return HttpResponse('Invalid header found.')
#             return redirect('accounts:thanks')
#         return HttpResponse('Make sure all fields are entered and valid.')
#     return render(request, 'contact/send_email.html', {'form': form_class,})



## access dla django:  https://myaccount.google.com/lesssecureapps?pli=1


# https://hellowebbooks.com/news/tutorial-setting-up-a-contact-form-with-django/
def send_email(request):
    form_class = ContactForm

    if request.method == 'POST':
        form = form_class(data=request.POST)

        if form.is_valid():
            subject = request.POST.get('subject', '')
            from_email = request.POST.get('from_email', '')
            form_content = request.POST.get('form_content', '')
            template = get_template('contact/contact_template.txt')

            context = {
                'subject': subject,
                'from_email': from_email,
                'form_content': form_content,
            }

            content = template.render(context)
            # print(content) ## drukuje do konsoli

            message= 'We received a message: `'+form_content+'`'+' from ' +str(request.user) + ' ' + from_email + '. If you are not the sender, please let us know. Thank you.'

            email = EmailMessage(
                subject,
                message,
                settings.DEFAULT_FROM_EMAIL,
                to=[from_email],
                headers = {'Reply-To': from_email, }
            )
            try:
                email.send()
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('accounts:thanks')
        return HttpResponse('Make sure all fields are entered and valid.')
    return render(request, 'contact/send_email.html', {'form': form_class,})




class CombinedEmailBackend(BaseEmailBackend):
    def send_messages(self, email_message):
        for backend in getattr(settings, "EMAIL_BACKEND_LIST", []):
            get_connection(backend).send_messages(email_message)
        return len(email_message)




def send_email2(request):
    form_class = ContactForm

    if request.method == 'POST':
        form = form_class(data=request.POST)

        if form.is_valid():
            subject = form.cleaned_data['subject']
            form_content = form.cleaned_data['form_content']
            form_content = form_content + "    "+str(datetime.date.today())
            from_email = form.cleaned_data['from_email']

            context = {
                'subject': subject,

templates/accounts/base_accounts.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
  <div class="container">
   

    {% block content %}

    {% endblock %}


  </div>
{% endblock %}

templates/accounts/deleted.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
  <div class="container">
    <h4 class="text-center logo my-4">
    You have deleted your account.
        <br>
        It was nice to know you.
    </h4>


    {% block content %}

    {% endblock %}


  </div>
{% endblock %}

templates/accounts/detail-update-view.html
{% extends "base.html" %}
{% load static %}
{% block title %}Update{% endblock %}

{% block content %}
<div class='col-12 col-md-6 mx-auto'>
{% if title %}<h1 class='my-3'>{{ title }}</h1>{% endif %}
<form method='POST' action='{% if action_url %}{{ action_url }}{% endif %}'> {% csrf_token %}
    {% if next_url %}
    <input type='hidden' name='next' value='{{ next_url }}' />
    {% endif %}

 {% include 'includes/form.html' %}

    <label for='email'>Email</label>
  <input type='text' id='email' class='form-control disabled' value='{{ request.user.email }}' disabled="disabled" /><span class='help-text'>Cannot change email</span><br/>
  <button type='submit' class='btn btn-default my-3'>Save</button>
  <a href=''>Change Password</a>
</form>
</div>
{% endblock %}

templates/accounts/home.cards.html
{% extends "base.html" %}

{% block content %}
<div class='row justify-content-center'>
<div class='col-12'>
<h1>Your Profile</h1>
<hr/>
</div>


   <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12  col" style="margin-bottom: 20px;">
    <div class="card transpar" style="">
      <div class="card-body">
        <h4 class="card-title">Support</h4>
            <div class='list-group'>
                <a class='list-group-item' href=''></a>
                <a class='list-group-item' href=''></a>
            </div>
      </div>
    </div>
</div>



<div class='col-xs-12 col-sm-12 col-md-12 col-lg-12  col" style="margin-bottom: 20px;' id='billing'>
    <div class="card transpar">
      <div class="card-body">
        <h4 class="card-title">Billing</h4>
            <div class='list-group'>
                <a class='list-group-item' href=''>orders:list Orders</a>
                <a class='list-group-item' href=''>billing-payment-method  Payment Methods</a>
                <a class='list-group-item' href=''>Addresses</a>


            </div>
      </div>
    </div>
</div>


<div class='col-xs-12 col-sm-12 col-md-12 col-lg-12  col" style="margin-bottom: 20px;'>
    <div class="card transpar">
      <div class="card-body">
        <h4 class="card-title">Account Details</h4>
            <div class='list-group'>
                <a class='list-group-item' href='{% url "accounts:user-update" %}'>Update Details</a>
                <a class='list-group-item' href=''>Change Password</a>
                <a class='list-group-item' href='{% url "sellers:dashboard" %}'>Library</a>

            </div>

      </div>
    </div>
</div>


<div class='col-xs-12 col-sm-12 col-md-12 col-lg-12  col" style="margin-bottom: 20px;'>
    <div class="card transpar">
      <div class="card-body">
        <h4 class="card-title">Preferences</h4>
            <div class='list-group'>
                <a class='list-group-item' href=''>Email Marketing</a>

            </div>

      </div>
    </div>
</div>


<div class='col-xs-12 col-sm-12 col-md-12 col-lg-12  col" style="margin-bottom: 20px;'>
    <div class="card transpar">
      <div class="card-body">
        <h4 class="card-title">History</h4>
              <div class='list-group'>
                <a class='list-group-item' href=''>Products</a>
            </div>
      </div>
    </div>
</div>
</div>

{% endblock %}

templates/accounts/home.html
{% extends "base.html" %}

{% block content %}
<div class='row justify-content-center'>
<div class='col-12'>
<h1>Your Profile</h1>
<hr/>
</div>

{% if request.user.is_authenticated %}


<div class="col-xs-12 col-sm-12 col-md-12 col-lg-6  col" style="padding-bottom: 10px;  padding-top: 10px;">
    <div class="card profile_card">
      <div class="card-body">
       <div class='list-group'>

<a class='btn btn-outline-dark btn-sm' style="padding-bottom: 10px;  padding-top: 10px;" href='{% url "library" %}'>My Purchases</a>
<a class='btn btn-outline-dark btn-sm' style="padding-bottom: 10px;  padding-top: 10px;" href='{% url "sellers:dashboard" %}'>My Sales</a>
<a class='btn btn-outline-dark btn-sm' style="padding-bottom: 10px;  padding-top: 10px;" href=''>Billing Address</a>
<a class='btn btn-outline-dark btn-sm' style="padding-bottom: 10px;  padding-top: 10px;" href=''>Payment Methods</a>
<a class='btn btn-outline-dark btn-sm' style="padding-bottom: 10px;  padding-top: 10px;" href='{% url "accounts:password_reset"  %}'>Change Password</a>

            </div>
      </div>
    </div>
</div>

{% endif %}


{% endblock %}

templates/accounts/login.html
{% extends 'accounts/base_accounts.html' %}

{% block title %}Log In{% endblock title %}

{% block style %}

## odwijajace sie osle ucho:
#osle_ucho {
    border: 1px solid black;
    -webkit-animation: mymove 15s infinite; /* Safari 4.0 - 8.0 */
    animation: mymove 15s infinite;
}
@keyframes mymove {
    50% { border-top-right-radius: 150px;}
}

/* Safari 4.0 - 8.0 */
@-webkit-keyframes mymove { 50% {border-top-right-radius: 150px;}

{% endblock style %}

{% block content %}



    <div class="row justify-content-center">
      <div class="col-lg-4 col-md-6 col-sm-8">
        <div id="osle_ucho" class="card  diagonal_gradient"
        style="border: 1px solid black;
        -webkit-animation: mymove 5s infinite; /* Safari 4.0 - 8.0 */
        animation: mymove 5s infinite;">
          <div class="card-body">
            <h3 class="card-title">Log in</h3>

            <form method="post" novalidate>
              {% csrf_token %}

<input type="hidden" name="next" value="{{next}}"><!--ta linijka to ukryta wlasciwosc LoginView  - sprawia, ze po zalogowaniu wskoczysz na strone z ktorej zostales zmuszony do zalogowania -->

              {% include 'includes/form.html' %}

              <button type="submit" class="btn btn-primary btn-block" >Log in</button>
            </form>
          </div>

          <div class="card-footer text-muted text-center">
            <a href="{% url 'accounts:signup' %}">Sign up</a> Free
          </div>
        </div>

        <div class="text-center py-2">

          <small>
            <a href="{% url 'accounts:password_reset' %}" class="text-muted">Password reset</a>
          </small>

        </div>

      </div>
    </div>



{% endblock %}

templates/accounts/my_account.html
{% extends 'base.html' %}

{% block title %}My account{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">My account</li>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <form method="POST" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">Save changes</button>
      </form>
    </div>
  </div>
{% endblock %}

templates/accounts/password_change.html
{% extends 'base.html' %}

{% block title %}Change password{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Change password</li>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">

      <form method="post" novalidate>
        {% csrf_token %}

        {% include 'includes/form.html' %}

        <button type="submit" class="btn btn-success">Change password</button>
      </form>

    </div>
  </div>
{% endblock %}

templates/accounts/password_reset.html
{% extends 'accounts/base_accounts.html' %}

{% block title %}Password reset{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title text-center">Reset your password</h3>
          <p>Enter your email address and we will send you a link to reset your password.</p>

          <form method="post" novalidate>
            {% csrf_token %}

            {% include 'includes/form.html' %}

            <button type="submit" class="btn btn-primary btn-block">Send password reset email<a href="" style="text-decoration: none;"></a></button>

            <!--accounts:send_my_email-->
          </form>

        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/accounts/password_reset_confirm.html
{% extends 'accounts/base_accounts.html' %}

{% block title %}
  {% if validlink %}
    Change password for {{ form.user.username }}
  {% else %}
    Reset your password
  {% endif %}
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          {% if validlink %}
            <h3 class="card-title">Change password for @{{ form.user.username }}</h3>


        <form method="post" novalidate>
              {% csrf_token %}

                  {% include 'includes/form.html' %}

            <button type="submit" class="btn btn-success btn-block">
                Change password</button>
        </form>


          {% else %}
            <h3 class="card-title">Reset your password</h3>
            <div class="alert alert-danger" role="alert">
              It looks like you clicked on an invalid password reset link. Please try again.
            </div>
            <a href="{% url 'accounts:password_reset' %}" class="btn btn-secondary btn-block">Request a new password reset link</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/accounts/password_reset_email.html
Hi there,

Someone asked for a password reset for the email address {{ email }}.
Follow the link below:
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

In case you forgot your Django Boards username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL
in a new browser window instead.

If you've received this mail in error, it's likely that another user entered
your email address by mistake while trying to reset a password. If you didn't
initiate the request, you don't need to take any further action and can safely
disregard this email.

Thanks,

The Django Boards Team

templates/accounts/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
  <h3>Forgot password</h3>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
{% endblock %}

templates/accounts/signout.html
{% extends 'base.html' %}

{% block title %}My account{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Delete my account</li>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <form method="POST" novalidate>
        {% csrf_token %}

        Are you sure you want to delete your account?

        <button type="submit" class="btn btn-warning">Save changes</button>
      </form>
    </div>
  </div>
{% endblock %}

templates/accounts/signup.html
{% extends 'accounts/base_accounts.html' %}

{% block title %}Sign Up{% endblock title %}


{% block content %}


    <div class="row justify-content-center">
      <div class="col-lg-8 col-md-10 col-sm-12">
        <div class="card">
          <div class="card-body">
            <h3 class="card-title">Sign up</h3>
            <form method="post" novalidate>
              {% csrf_token %}


                  {% include 'includes/form.html' %}


                <button type="submit" class="btn btn-primary btn-block">Create an account</button>
            </form>
          </div>

          <div class="card-footer text-muted text-center">
            Already have an account? <a href="{% url 'accounts:login'  %}">Log in</a>
          </div>
        </div>
      </div>
    </div>




{% endblock  %}