digitalmarket/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import include, path
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

import products.views
from products.views import UserLibraryListView
import tags.views
import dashboard.views
from dashboard.views import DashboardView
import checkout.views
from checkout.views import CheckoutTestView, CheckoutAjaxView
import sellers.views
from accounts import views as accounts_views

from django.conf.urls import include, url

from django.views.generic import TemplateView

from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

# Debug Toolbar: 
if settings.DEBUG:
    import debug_toolbar


urlpatterns = [
    path('kwakwa/', admin.site.urls, name='admin'),
    # https://docs.djangoproject.com/en/2.1/ref/contrib/admin/#hooking-adminsite-to-urlconf
    path('accounts/', include('accounts.urls')),
    path('', dashboard.views.DashboardView.as_view(), name='dashboard'),
    path('404', products.views.index, name='index'),
    path('checkout/', checkout.views.CheckoutAjaxView.as_view(), name='checkout'),
    path('library/', products.views.UserLibraryListView.as_view(), name='library'),
    path('products/', include('products.urls', namespace='products')),
    path('seller/', include('sellers.urls', namespace='sellers')),
    path('tags/', include('tags.urls', namespace='tags')),
    path('test/', checkout.views.CheckoutTestView.as_view(), name='test'),
]

handler404 = 'products.views.error_404_view'

urlpatterns += [
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico'), ), name="favicon" ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
    urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls)),]

if not settings.DEBUG:
    urlpatterns += [
        path('anymail/', include('anymail.urls')),  ## for sendgrid webhooks  # production only
    ]

products/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.urls import include, path
from django.views.generic.base import RedirectView

from django.conf.urls.static import static
from django.contrib import admin
from . import views
from .views import *
# (
#     ProductCreateView,
#     ProductDeleteView,
#     ProductDetailView,
#     ProductDownloadView,
#     ProductListView,
#     ProductUpdateView,
#     ProductRatingAjaxView,
#     VendorListView,
#     CuratedProducts_ListView,
#     )
#

app_name="products"

urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('curated/<slug>/', CuratedProductsListView.as_view(), name='curated_list'),
    path('ajax/rating/', ProductRatingAjaxView.as_view(), name='ajax_rating'),
    ## session check:
    path('all', articles, name='articles'),
    path('get/<int:pk>', article, name='article'),
    path('language/<language>/', language),
    # /products/language/en-us/
    # /products/language/pl/
    path('vendor/', RedirectView.as_view(pattern_name='products:list'), name='vendor_list'),
    path('vendor/<vendor_name>/', VendorListView.as_view(), name='vendor_detail'),
    path('<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('<slug>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('<int:pk>/', ProductDetailView.as_view(), name='detail'),
    path('<slug>/', ProductDetailView.as_view(), name='detail_slug'),
    path('<int:pk>/download/', ProductDownloadView.as_view(), name='download'),
    path('<slug>/download/', ProductDownloadView.as_view(), name='download_slug'),
    path('<int:pk>/edit/', ProductUpdateView.as_view(), name='update'),
    path('<slug>/edit/', ProductUpdateView.as_view(), name='update_slug'),
]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tags/urls.py
from django.conf import settings
from django.conf.urls import url  #include, 
from django.conf.urls.static import static
from django.urls import include, path 
from . import views 
from .views import TagDetailView, TagListView 


app_name="tags"

urlpatterns = [
    path('', TagListView.as_view(), name='list'),   # tag_list.html
    path('<int:pk>/', TagDetailView.as_view(), name='detail'),  # tag_detail.html
    path('<slug>/', TagDetailView.as_view(), name='detail_slug'),  # tag_detail.html
] 

billing/models.py
from django.conf import settings
from django.db import models
from products.models import Product

'''
buyer's transaction
user (=buyer) purchases from seller (Product.seller)
'''
class Transaction(models.Model):
	user=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

	product =models.ForeignKey(Product, on_delete=models.CASCADE)
	price = models.DecimalField(max_digits=7, decimal_places=2, default=9.99, blank=True)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	success = models.BooleanField(default=True)

	def __str__(self):
		return "%s" %(self.id)

	class Meta:
		ordering = ['-timestamp']

products/models.py
import sys
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from django.db import models
from django.db.models import Avg
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver

from django.utils.text import slugify
from django.urls import reverse
from sellers.models import SellerAccount

import os
import shutil
from PIL import Image
import random
from django.core.files import File


from django.db import IntegrityError
from django.shortcuts import render_to_response


from django.db import models
from django.db.models.signals import post_delete


User=settings.AUTH_USER_MODEL


def my_media_location(instance, filename):
    konc = ['png','jpg','jpeg','gif']
    try:
        name_ = filename.split('.')
        nazwa = instance.slug
        koncowka = name_[len(name_)-1]
        if koncowka in konc:
            nowanazwa = "%s.%s" % (nazwa, koncowka)
            return "%s/%s" % (instance.slug, nowanazwa)
        else:
            # print('We accept only png, jpg, jpeg and gif files')
            return 0
    except:
        # print('File is missing')
        return 0
        # reject the files 


# def download_media_location(instance, filename):
#     return "%s/%s" %(instance.slug, filename)


class Product(models.Model):
    seller=models.ForeignKey(SellerAccount, default=2, on_delete=models.CASCADE)
    media = models.ImageField(blank=True, null=True, upload_to=my_media_location)

    title = models.CharField(max_length=120)
    slug=models.SlugField(blank=True, unique=True)
    description = models.TextField(max_length=220)
    price = models.DecimalField(max_digits=7, decimal_places=2, default=9.99, blank=True)
    sale_price = models.DecimalField(max_digits=7, decimal_places=2, default=9.99, blank=True)
    sale_active = models.BooleanField(default=False)

    def get_absolute_url(self):
        view_name = "products:detail_slug"
        return reverse(view_name, kwargs={"slug":self.slug})



    def get_edit_url(self):
        view_name = "sellers:product_edit"
        return reverse(view_name, kwargs={"pk":self.id})



    def __str__(self):
        return self.title


    def get_download(self):
        view_name = "products:download_slug"
        url = reverse(view_name, kwargs={"slug":self.slug})
        return url

    @property
    def get_price(self):
        if self.sale_price and self.sale_active:
            return self.sale_price
        return self.price



    def get_averrat(self):
        p = None
        one = 0
        rat = 0
        try:
            p = Product.objects.get(title=self)
            one = p.productrating_set.aggregate(Avg('rating'))
            rat = '{:.2f}'.format(one['rating__avg'])
        except:
            one = 0
            rat = 0
        return rat


    def get_html_price(self):
        price = self.get_price
        if price == self.sale_price:
            return self.price
        elif price < self.sale_price:
            return self.sale_price
        else:
            return " <span>%s</span> <span style='color: maroon; text-decoration: line-through;'>%s</span>" %(self.sale_price, self.price)



def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug

    qs = Product.objects.filter(slug=slug)
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug




def product_pre_save_receiver(sender,instance,*args,**kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(product_pre_save_receiver, sender=Product)



def create_new_thumb(media_path, instance, owner_slug, max_length, max_width):
    filename = os.path.basename(media_path)
    thumb = Image.open(media_path)
    size = (max_length, max_width)
    thumb.thumbnail(size, Image.ANTIALIAS)
    temp_loc = "%s/%s/tmp" %(settings.MEDIA_ROOT, owner_slug)
    if not os.path.exists(temp_loc):
        os.makedirs(temp_loc)
    temp_file_path = os.path.join(temp_loc, filename)
    temp_image = open(temp_file_path, "wb")
    thumb.save(temp_image)
    thumb_data = open(temp_file_path, "r+b")  # 'rb+'
    thumb_file = File(thumb_data)

    instance.media.save(filename, thumb_file)
    shutil.rmtree(temp_loc, ignore_errors=True)
    return True



def product_post_save_receiver(sender, instance, created, *args, **kwargs):
    if instance.media:
        try:
            hd, hd_created = Thumbnail.objects.get_or_create(product=instance, type='hd')
            sd, sd_created = Thumbnail.objects.get_or_create(product=instance, type='sd')
            micro, micro_created = Thumbnail.objects.get_or_create(product=instance, type='micro')
            hd_max=(500,500)
            sd_max=(350,350)
            micro_max=(150,150)
            media_path = instance.media.path
            owner_slug = instance.slug
            if hd_created:
                try:
                    create_new_thumb(media_path, hd, owner_slug, hd_max[0], hd_max[1])
                except:
                    pass
            if sd_created:
                try:
                    create_new_thumb(media_path, sd, owner_slug, sd_max[0], sd_max[1])
                except:
                    pass
            if micro_created:
                try:
                    create_new_thumb(media_path, micro, owner_slug, micro_max[0], micro_max[1])
                except:
                    pass
        except:
            print('No media in Product instance')

post_save.connect(product_post_save_receiver, sender=Product)



###############################################
# https://djangosnippets.org/snippets/10638/
@receiver(models.signals.post_delete, sender=Product)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem
    when corresponding `MediaFile` object is deleted.
    """
    if instance.media:
        if os.path.isfile(instance.media.path):
            os.remove(instance.media.path)

@receiver(models.signals.pre_save, sender=Product)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """
    Deletes old file from filesystem
    when corresponding `MediaFile` object is updated
    with new file.
    """
    if not instance.pk:
        return False

    try:
        old_file = sender.objects.get(pk=instance.pk).media
    except sender.DoesNotExist:
        return False

    new_file = instance.media
    if not old_file == new_file:
        if os.path.isfile(old_file.path):
            os.remove(old_file.path)
###############################################













def thumbnail_location(instance, filename):
    name_ = filename.split('.')
    nazwa = instance.product.slug
    koncowka = name_[1]
    nowanazwa = "%s.%s" % (nazwa, koncowka)
    return "%s/%s" %(nazwa, nowanazwa)


THUMB_CHOICES=(
    ("hd","HD"),
    ("sd", "SD"),
    ("micro", "Micro"),
    )


class Thumbnail(models.Model):
    product = models.ForeignKey("Product", on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE)  ##this is the uploading user
    type = models.CharField(max_length=20, choices=THUMB_CHOICES, default='hd')
    height = models.CharField(max_length=20, null=True, blank=True)
    width = models.CharField(max_length=20, null=True, blank=True)
    media = models.ImageField(
        height_field = "height",
        width_field = "width",
        blank=True, null=True,
        upload_to=thumbnail_location)

    def __str__(self):
        if self.media:
            return "%s" % (self.media.path)
        else:
            return "%s" %("empty")

    @property
    def image_url(self):
        if self.media and hasattr(self.media, 'url'):
            return self.media.url



##############################################
# https://djangosnippets.org/snippets/10638/
@receiver(models.signals.post_delete, sender=Thumbnail)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem
    when corresponding `MediaFile` object is deleted.
    """
    if instance.media:
        if os.path.isfile(instance.media.path):
            os.remove(instance.media.path)

@receiver(models.signals.pre_save, sender=Thumbnail)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """
    Deletes old file from filesystem
    when corresponding `MediaFile` object is updated
    with new file.
    """
    if not instance.pk:
        return False

    try:
        old_file = sender.objects.get(pk=instance.pk).media
    except sender.DoesNotExist:
        return False

    new_file = instance.media
    if not old_file == new_file:
        if os.path.isfile(old_file.path):
            os.remove(old_file.path)
##############################################








class MyProducts(models.Model):
    user=models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, blank=True)

    def __str__(self):
        return "%s" %(self.products.count())


    class Meta:
        verbose_name = "My Products"
        verbose_name_plural = "My Products"







class ProductRating(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product= models.ForeignKey(Product, on_delete=models.CASCADE)
    rating=models.IntegerField(null=True, blank=True)
    verified=models.BooleanField(default=False)

    def __str__(self):
        return "%s" %(self.rating)


class CuratedProducts(models.Model):
    section_name = models.CharField(max_length=120)
    products = models.ManyToManyField(Product, blank=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.section_name

    class Meta:
        verbose_name = "Curated products"
        verbose_name_plural = "Curated products"

templates/products/curated_list.html
{% extends "base.html" %}
{% block style %} {% endblock style %}
{% load get_thumbnail %}
{% load static from staticfiles %}
{% load staticfiles %}
{% load static %}
{% load bootstrap4 %}
{% load get_thumbnail %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}


{%block title%}{{object}} {%endblock title%}


{%block content%}

<div class="row" style="margin-bottom: 10px; ">
<h1>{{ object}}</h1>
</div>


{%  include 'search.html'  %}



<div class="row" style="margin-bottom: 10px; ">

{% include "products/product_list_snippet.html" with product_list=object_list %}

</div>





{% endblock content %}

templates/products/library_list.html
{% extends "base.html" %}
{% block style %} {% endblock style %}
{% load get_thumbnail %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}


{%block title%}My Purchases{%endblock title%}

{%block content%}


<div class="row">
<h1>My Purchases</h1>
</div>

<hr class="invisible">


{% include 'search.html' %}

<hr>

<div class="row" style="margin-bottom: 10px;">

{% for instance in product_list %}


 <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3  col1" style="margin-bottom: 15px;">
		{% if instance|get_thumbnail:'micro' %}
		<a href="{{instance.media.url}}">
   		<img src="{{ instance|get_thumbnail:'micro' }}"></a>

  <div style="vertical-align: text-bottom"><a href="{{instance.get_absolute_url}}">{{instance.title}}</a>

 <a href="{% url 'products:download_slug' instance.slug %}"><span class="ikona_download"></span></a>
 


{% endif %}
</div>
</div>






{% empty %}
<li>No products yet.</li>
{% endfor %}

</div>









{% endblock content %} 

templates/products/product_detail.html
{% extends "base.html" %}
{% block style %}

<style>
/* cudze  - blok na dole */
.glyphicon { margin-right:5px; }
.rating .glyphicon {font-size: 20px; }
.rating-num { margin-top:0px;font-size: 40px; }
.progress { 
  margin-bottom: 5px; 
  border: solid gray 1px;
  border-radius: 3px;
    -moz-border-radius:3px;
    -webkit-border-radius:3px;
}

.mybak {  }
.rating-desc {  margin-top: 10px;  }
.rating-desc .col-md-3 {padding-right: 0px; }
.sr-only { margin-left: 5px;  overflow: visible;  clip: auto; }

.picture { margin-bottom: 5px; }


/* mitch */
.fieldset_moj {
    display: block;
    margin-left: 2px;
    margin-right: 2px;
    padding-top: 0.35em;
    padding-bottom: 0.625em;
    padding-left: 0.75em;
    padding-right: 0.75em;

/*	border: 0.01px solid white;
 	border-style: hidden;  #ja dopisalam
	border-color: white;  #ja dopisalam
	border-style: none;  #ja dopisalam */
}

.rating {    float:left; }
/* :not(:checked) is a filter, so that browsers that don’t support :checked don’t
   follow these rules. Every browser that supports :checked also supports :not(), so
   it doesn’t make the test unnecessarily selective */
.rating:not(:checked) > input {
    position:absolute;
    top:-9999px;
    clip:rect(0,0,0,0);
}

.rating:not(:checked) > label {
    float:right;
    width:1em;
    padding:0 .1em;
    overflow:hidden;
    white-space:nowrap;
    cursor:pointer;
    font-size:200%;
    line-height:1.2;
    color: gainsboro;
/*    text-shadow:1px 1px #bbb, 2px 2px #666, .1em .1em .2em rgba(0,0,0,.5);  */
}

.rating:not(:checked) > label:before {
    content: '★ ';
}

.rating > input:checked ~ label {
    color: maroon;
/*    text-shadow:1px 1px #c60, 2px 2px #940, .1em .1em .2em rgba(0,0,0,.5);  */
}

.rating:not(:checked) > label:hover,
.rating:not(:checked) > label:hover ~ label {
    color: maroon;
/*    text-shadow:1px 1px maroon, 2px 2px #B57340, .1em .1em .2em rgba(0,0,0,.5);*/
}

.rating > input:checked + label:hover,
.rating > input:checked + label:hover ~ label,
.rating > input:checked ~ label:hover,
.rating > input:checked ~ label:hover ~ label,
.rating > label:hover ~ input:checked ~ label {
    color: maroon;
 /*     text-shadow:0px 0px white, 2px 2px white, .1em .1em .2em rgba(0,0,0,.5);  */
}

.rating > label:active {
    position:relative;
    top:2px;
    left:2px;
}

</style>
{% endblock style %}






<script>
$(document).ready(function(){
   {% block jquery %}

$(".rating input[value='{{my_rating}}']").attr("checked", "checked")

$(".rating input[type='radio']").click(function(event){
    var inputValue = $(this).val()
    console.log(inputValue)

var request = $.ajax({
method: "POST",
url: "{% url 'products:ajax_rating' %}",
data: {
  product_id: "{{ object.id }}",
  rating_value: inputValue,
}  })
request.done(function(data){

})
request.fail(function(jqXHR, textStatus){

  console.log('error', jqXHR.status)

if (jqXHR.status == 404){
   console.log(jqXHR.status )
  } else if (jqXHR.status == 401){
    console.log(jqXHR.status )
  } else if  (jqXHR.status == 403){
      console.log(jqXHR.status )
  }
  else {
      console.log(jqXHR.status )
  }  })
})



   $("#purchase-btn").click(function(event){
    event.preventDefault()
    var purchaseBtn = $(this)
    $("#dialog-confirm").fadeIn("300")
    $("#dialog-confirm").dialog({
      resizable: false,
      height: 350,
      width: 350,
      modal: true,
      buttons: {
        1: {
          id: "close",
          text: "Confirm",
          click: function(){
                console.log("confirm")
                console.log("teraz odbywa sie transakcja")

var request = $.ajax({
  method: "POST",
  url: "{% url 'checkout' %}",
  data: {
    product_id: "{{ object.id }}",
  }
})

request.done(function(data){
  console.log(data.download)
  purchaseBtn.before("<p><a href='" + data.download + "'>Download</a></p>")
  purchaseBtn.fadeOut(100)

console.log("working...")
// if (data.works){
//  $("#content").html(data.time)
// }


})
request.fail(function(jqXHR, textStatus){
if (jqXHR.status == 404){
  alert("Page not found!")
  } else if (jqXHR.status == 401){
    alert("Log in")
  }
  else {
    alert("There was an error with your request.")
  }
})


            $(this).dialog("close")
          },
          class: "buy-btn"
        },
        2: {
          id: "close",
          text: "Cancel",
          click: function(){
            $(this).dialog("close")
          },
          class: "cancel-btn"
        } }

    })
    })
   {% endblock jquery %}
});

var csrftoken = Cookies.get('csrftoken');
</script>



{% load get_thumbnail %}
{% load static from staticfiles %}
{% load staticfiles %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}



{%block title%} {{object.slug}} {%endblock title%}

{%block content%}





{% if request.user.is_authenticated %}
{% if object %}

<p class="row" style="margin-bottom: 10px;">

<h1>{{object.title}}</h1>


<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6  col2">

<i>{{object.description}}</i>  by <a href="{{ object.seller.get_absolute_url }}"> {{object.seller.user.username}} </a><br>



	{% if request.user.username == object.seller.user.username %}
    <div class="btn btn-light">
    <a href="{{object.get_edit_url}}">Edit</a> | <a href="{% url 'products:product_delete' pk=object.pk  %}">Delete</a></div>
    <br>
    {% endif %}


<p>{{object.get_html_price|safe}} Peanuts</p>
<p>Purchases: {{ object.transaction_set.count }} </p>


{%  if not request.user == object.seller.user %}
  <strong>My Rating: {{my_rating}} </strong> <br>
  {% endif %}

    
<div class="fieldset_moj rating small" >
    <!-- <legend>Please rate:</legend> -->
<!--<span class="glyphicon glyphicon-star"> </span>-->
<!--</span><span class="glyphicon glyphicon-star-empty"> </span>-->

  <input type="radio" id="star5" name="rating"  value="5" /><label for="star5" title="Great">5 stars</label>
  <input type="radio" id="star4" name="rating" value="4" /><label for="star4" title="Pretty good">4 stars</label>
  <input type="radio" id="star3" name="rating" value="3" /><label for="star3" title="Middle">3 stars</label>
  <input type="radio" id="star2" name="rating" value="2" /><label for="star2" title="Rather bad">2 stars</label>
  <input type="radio" id="star1" name="rating" value="1" /><label for="star1" title="Too bad">1 star</label>
</div>




{% if object|get_thumbnail:'hd' %}
<div class="">
  <a href="{{object.media.url}}">
   <img src="{{ object|get_thumbnail:'hd' }}"></a>
 </div>
 {% elif object|get_thumbnail:'sd' %}
    <div class="">
    <a href="{{object.media.url}}">
    <img src="{{ object|get_thumbnail:'sd' }}"></a>
    </div>
 {% else %} Temporarily the picture is off

{% endif %}

</div>


<!-- col1 -->
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

<h2> </h2>
{% if object in request.user.myproducts.products.all %}
{% if object.media %}

  <!-- <div class="btn btn-light btn-sm" style="margin-bottom: 5px;"><a href="{{object.get_download}}">Download</a></div> -->
  <!-- <div class="btn btn-light" style="margin-bottom: 5px;"><a href="{{object.get_download}}?preview=True">Preview</a></div> -->
  <!-- <div class="btn btn-light" style="margin-bottom: 5px;"><a href="{% url 'products:download_slug' slug=object.slug %}">Download (inne linki)</a></div> -->

  <br>
{% endif %}
{% endif %}

<div class="purchase-area" style="margin: 15px 15px 15px 15px;">

{% if request.user.username != object.seller.user.username %}
  <div id="purchase-btn" class="btn btn-info btn-lg" style="margin-bottom: 30px" href="#"><span>Purchase</span></div>
  <div id='dialog-confirm' title='Confirm Purchase' style='display:none'>
    <p>Your card on file will be charged. Do you like to proceed?</p>
  </div>
{% endif %}
  <!--{% else %}-->
  <!--<div id="purchase-btn" class="btn btn-warning" href="#">Pre-order</div>-->
  <p>Item currently not available</p>
  <br>
</div>

{% endif %}
<!-- end col1  -->

</div>
<br/>



<div class="col-xs-12 col-sm-12 col-md-9 col-lg-6">

{% if rating_avg.rating__avg %}

<strong style="color:maroon;">Average rating: {{rating_avg.rating__avg|floatformat:2 }}</strong>. Rated by {{rating_avg.rating__count}} 
<span style="color:black" class="glyphicon glyphicon-user"> </span> 
 {% if rating_avg.rating__count > 1 %} users: {% else %} user: {% endif %}<br>

<!--dla kazdego usera ktory ocenil - rating od najlepszego do najgorszego -->
{% for one in ocenki %}

            <div class="row rating-desc">
                <div class="col-xs-3 col-md-3 col-lg-3">
                    <span class="glyphicon glyphicon-star"></span>{{ one.username }} ({{ one.ocenka}})
                </div>
                <div class="col-xs-9 col-md-9 col-lg-9">
                    <div class="progress progress-striped">

                        <!--progress-bar-success-->
                        <div class="progress-bar mybak" role="progressbar" aria-valuenow="100-{{ one.procent_slupka }}"  aria-valuemin="0" aria-valuemax="100" style="width:{{ one.procent_slupka }}%">
                            <span class="sr-only">{{ one.procent_slupka }}% </span>
                            {{ one.procent_slupka }}%
                        </div> 
                    </div>
                </div>
            </div>
{% endfor %}


{% else %} No rating yet.
{% endif %}

</div>


<br>

 


{%else%}
<div class="">
{{block.super}}
	</div>

{%endif%}


{% endblock content %}

templates/products/product_list_snippet.html
{% load get_thumbnail %}





{% for instance in product_list %}




<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3  col2" style="padding-bottom: 60px; ">




<span class="quiet photo-title">
	<a href="{{instance.get_absolute_url}}" style="white-space: nowrap;">{{instance.title}}</a>
</span>

	 <div class="clearfix">
	{% if instance|get_thumbnail:'micro' %}
	 	    <a href="{{instance.get_absolute_url}}">
			<img src="{{ instance|get_thumbnail:'micro' }}"/>
			</a>
	{% else %}
		 <a href=""><img src="../static/img/waiting.png"/></a>
		 <!--{# "{% static 'img/waiting.png' %} #}-->
	{% endif %}
	 </div>


<span class="quiet price">{{instance.price}}</span>
{% if instance.seller.user.username == request.user.username %} <a class="" href="{% url 'products:update_slug' slug=instance.slug %}">Edit</a>
<!-- <a href="{{instance.get_edit_url}}">Edit2</a> -->
{% else %} <span class="quiet issuer-name">{{instance.seller}} </span>{% endif %}



</div>


{% empty %}


<li>No products yet.</li>
{% endfor %}