digitalmarket/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import include, path
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

import products.views
from products.views import UserLibraryListView
import tags.views
import dashboard.views
from dashboard.views import DashboardView
import checkout.views
from checkout.views import CheckoutTestView, CheckoutAjaxView
import sellers.views
from accounts import views as accounts_views

from django.conf.urls import include, url

from django.views.generic import TemplateView

from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

# Debug Toolbar: 
if settings.DEBUG:
    import debug_toolbar


urlpatterns = [
    path('kwakwa/', admin.site.urls, name='admin'),
    # https://docs.djangoproject.com/en/2.1/ref/contrib/admin/#hooking-adminsite-to-urlconf
    path('accounts/', include('accounts.urls')),
    path('', dashboard.views.DashboardView.as_view(), name='dashboard'),
    path('404', products.views.index, name='index'),
    path('checkout/', checkout.views.CheckoutAjaxView.as_view(), name='checkout'),
    path('library/', products.views.UserLibraryListView.as_view(), name='library'),
    path('products/', include('products.urls', namespace='products')),
    path('seller/', include('sellers.urls', namespace='sellers')),
    path('tags/', include('tags.urls', namespace='tags')),
    path('test/', checkout.views.CheckoutTestView.as_view(), name='test'),
]

handler404 = 'products.views.error_404_view'

urlpatterns += [
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico'), ), name="favicon" ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
    urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls)),]

if not settings.DEBUG:
    urlpatterns += [
        path('anymail/', include('anymail.urls')),  ## for sendgrid webhooks  # production only
    ]

products/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.urls import include, path
from django.views.generic.base import RedirectView

from django.conf.urls.static import static
from django.contrib import admin
from . import views
from .views import *
# (
#     ProductCreateView,
#     ProductDeleteView,
#     ProductDetailView,
#     ProductDownloadView,
#     ProductListView,
#     ProductUpdateView,
#     ProductRatingAjaxView,
#     VendorListView,
#     CuratedProducts_ListView,
#     )
#

app_name="products"

urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('curated/<slug>/', CuratedProductsListView.as_view(), name='curated_list'),
    path('ajax/rating/', ProductRatingAjaxView.as_view(), name='ajax_rating'),
    ## session check:
    path('all', articles, name='articles'),
    path('get/<int:pk>', article, name='article'),
    path('language/<language>/', language),
    # /products/language/en-us/
    # /products/language/pl/
    path('vendor/', RedirectView.as_view(pattern_name='products:list'), name='vendor_list'),
    path('vendor/<vendor_name>/', VendorListView.as_view(), name='vendor_detail'),
    path('<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('<slug>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('<int:pk>/', ProductDetailView.as_view(), name='detail'),
    path('<slug>/', ProductDetailView.as_view(), name='detail_slug'),
    path('<int:pk>/download/', ProductDownloadView.as_view(), name='download'),
    path('<slug>/download/', ProductDownloadView.as_view(), name='download_slug'),
    path('<int:pk>/edit/', ProductUpdateView.as_view(), name='update'),
    path('<slug>/edit/', ProductUpdateView.as_view(), name='update_slug'),
]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sellers/urls.py
from django.conf import settings
#from django.conf.urls import url  #include, 
from django.urls import include, path 

from . import views 
from .views import (    SellerDashboard, SellerTransactionListView, SellerProductDetailRedirectView  )
from products.views import SellerProductListView, ProductUpdateView, ProductCreateView  #, create_view




app_name="sellers"

urlpatterns = [
    path('', SellerDashboard.as_view(), name='dashboard'),   
    path('products/add/', ProductCreateView.as_view(), name='product_create'),  # form.html    sellers:product_create
    #path('products/add/', create_view, name='product_create'),  # form.html    sellers:product_create
    path('products/', SellerProductListView.as_view(), name='product_list'),  # sellers/product_list_view.html   sellers:product_list
    path('products/<int:pk>/', SellerProductDetailRedirectView.as_view()), 
    path('products/<int:pk>/edit/', ProductUpdateView.as_view(), name='product_edit'), 
    path('transactions/', SellerTransactionListView.as_view(), name='transactions'), 
] 
# SellerProductDetailRedirectView

tags/urls.py
from django.conf import settings
from django.conf.urls import url  #include, 
from django.conf.urls.static import static
from django.urls import include, path 
from . import views 
from .views import TagDetailView, TagListView 


app_name="tags"

urlpatterns = [
    path('', TagListView.as_view(), name='list'),   # tag_list.html
    path('<int:pk>/', TagDetailView.as_view(), name='detail'),  # tag_detail.html
    path('<slug>/', TagDetailView.as_view(), name='detail_slug'),  # tag_detail.html
] 

billing/models.py
from django.conf import settings
from django.db import models
from products.models import Product

'''
buyer's transaction
user (=buyer) purchases from seller (Product.seller)
'''
class Transaction(models.Model):
	user=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

	product =models.ForeignKey(Product, on_delete=models.CASCADE)
	price = models.DecimalField(max_digits=7, decimal_places=2, default=9.99, blank=True)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	success = models.BooleanField(default=True)

	def __str__(self):
		return "%s" %(self.id)

	class Meta:
		ordering = ['-timestamp']

sellers/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse


class SellerAccount(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	managers_sellers=models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="managers_sellers", blank=True)
	active = models.BooleanField(default=False)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)


	def __str__(self):
		return str(self.user.username)

	class Meta:
		ordering = ['-timestamp']


	def get_absolute_url(self):
		view_name = "products:vendor_detail"
		return reverse(view_name, kwargs={"vendor_name":self.user.username})

dashboard/forms.py
from django import forms
from django.forms import TextInput
from products.models import Product


from products.models import *
from sellers.models import SellerAccount
from .mixins import DashboardSearchMixin
from django.db.models import Q, Avg, Count





class SearchForm(forms.ModelForm):
    class Meta:
        model = Product
        fields=['title', 'description']
        widgets = {'name' : TextInput(attrs={'class' : 'input',
                                             'placeholder' : 'Product',
                                             })}

sellers/forms.py
from django import forms


class NewSellerForm(forms.Form):
	agree = forms.BooleanField(label='Agree to Terms', widget=forms.CheckboxInput)

dashboard/views.py
import random
from django.shortcuts import render
from django.views.generic import View
from products.models import *
from sellers.models import SellerAccount
from .mixins import DashboardSearchMixin
from django.db.models import Q, Avg, Count
from braces import views

import json
from collections import OrderedDict
from django.http import HttpResponse
from .forms import SearchForm



class DashboardView(DashboardSearchMixin, View):
    template_name="dashboard/view.html"


    def get(self, request, *args, **kwargs):
        tag_views = None
        products = None
        sug_products = None
        top_tags = None

    #     curated = CuratedProducts.objects.filter(active=True).order_by("?")[:3]
    #     try:
    #         tag_views = request.user.tagview_set.all().order_by("-count")
    #     except:
    #         pass

    #     owned = None
    #     try:
    #         owned = request.user.myproducts.products.all()
    #     except:
    #         pass

    #     account=None
    #     try:
    #         account = SellerAccount.objects.filter(user=request.user).first()
    #     except:
    #         print(SellerAccount.objects.filter(user=request.user), "    dashboard views")

    #     my_forsale_prods = None
    #     try:
    #         my_forsale_prods = Product.objects.filter(seller=account)
    #     except:
    #         pass



    #     if tag_views:
    #         top_tags = [x.tag for x in tag_views]
    #         top_tags = sorted(top_tags, key=lambda x: random.random())
    #         sug_products = Product.objects.all()
    #         if my_forsale_prods:
    #             sug_products = sug_products.exclude(seller=account)

    #         if owned:
    #             sug_products = sug_products.exclude(pk__in=owned)

    #         filtered = sug_products.filter(tag__in=top_tags)
    #         if filtered.count() < 10:
    #             pass
    #         else:
    #             sug_products = filtered


    #         if sug_products.count() < 8:
    #             sug_products = sug_products.order_by("?")
    #         else:
    #             sug_products= sug_products.distinct()[:11]
    #             sug_products= sorted(sug_products, key = lambda x: random.random())



    #     favourite = []
    
    #     if request.user.is_authenticated:
    #         user=request.user

    #         data_list = [] 

    #         if user.tagview_set.count() > 0:
    #             for q in user.tagview_set.all():
    #                 data_list.append(q.count)

    #         new_list = []

    #         while data_list:
    #             maximum = data_list[0]  # arbitrary number in list 
    #             for x in data_list: 
    #                 if x > maximum:
    #                     maximum = x
    #             new_list.append(maximum)
    #             data_list.remove(maximum)    

    #         ## tylko najpopularniejsze:
    #         if len(new_list)>0:
    #             new_list = new_list[:7]
    #             for item in new_list:
    #                 tt = user.tagview_set.filter(count=item)[0]
    #                 # print(item, tt)
    #                 favourite.append(tt)


    #     context = {
    #         "top_tags":top_tags,
    #         "curated":curated,
    #         "sug_products":sug_products,
    #         "favourite":favourite
    #     }
        # return render(request, "dashboard/view.html", context )

        context = {}     
        return render(request, "dashboard/view.html", context )





def render_json_response(request, data, status=None):
    """response を JSON で返却"""
    json_str = json.dumps(data, ensure_ascii=False, indent=2)
    callback = request.GET.get('callback')
    if not callback:
        callback = request.POST.get('callback')
    if callback:
        json_str = "%s(%s)" % (callback, json_str)
        response = HttpResponse(json_str, content_type='application/javascript; charset=UTF-8', status=status)
    else:
        response = HttpResponse(json_str, content_type='application/json; charset=UTF-8', status=status)
    return response




def json_list(request):
    data = {}
    file = 'sellers_and_buyers_stock.json'
    data['selling'] = []
    data['buying'] = []

    uzytkown = SellerAccount.objects.select_related('user').all()
    buyers = []
    uniques = []
    sellerzy = []

    sellers= []

    for pps in Thumbnail.objects.select_related("product").all():
        if pps.product.description not in uniques:
            uniques.append(pps.product.description)
            sells = str(pps.product.seller)
            sellerzy.append(sells)
            what = str(pps.product.description)
            data['selling'].append({sells: what, })

            sellers_dict = OrderedDict([
                ('seller', sells),
                ('product', what),
            ])
            sellers.append(sellers_dict )


    for one in uzytkown:
        who = str(one.user)
        if who in sellerzy:
            how_many = one.user.myproducts
            for x in one.user.myproducts.products.all():
                what = str(x)
                data['buying'].append({who: what})
                buyers_dict = OrderedDict([
                    ('who', who),
                    ('product', what),
                    ('sellers', sellers)
                ])
                buyers.append(buyers_dict)



    with open(file, 'w') as outfile:
        json.dump(data, outfile)

    return render_json_response(request, data)

sellers/views.py
import datetime
import calendar
from django.db.models import Q, Avg, Count
from django.db.models import Count, Min, Max, Sum, Avg
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from digitalmarket.mixins import LoginRequiredMixin
from django.views.generic.edit import FormMixin
from django.views.generic.list import ListView
from django.views.generic.base import RedirectView

from .forms import NewSellerForm
from .models import SellerAccount
from sellers.mixins import SellerAccountMixin

from billing.models import Transaction
from products.models import Product
from braces import views

import datetime
from django.utils import timezone
from pytz import timezone




class SellerProductDetailRedirectView(RedirectView):
    permanent=True

    def get_redirect_url(self, *args, **kwargs):
        obj=get_object_or_404(Product, pk=kwargs['pk'])
        return obj.get_absolute_url()



class SellerTransactionListView(SellerAccountMixin, ListView):
    model=Transaction
    template_name="sellers/transaction_list_view.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['special'] = 'background-color: linen;'
        return context



class SellerDashboard(SellerAccountMixin, FormMixin, View):
    form_class = NewSellerForm
    success_url = "/seller"


    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            self.form_invalid(form)


    def get(self, request, *args, **kwargs):
        apply_form = self.get_form()
        account = self.get_account()
        exists = account
        active = None
        context = {}

        if exists:
            active =  account.active

        if exists and active:
            context["title"] = "My Sales"
            context["products"] = self.get_products()
            transactions_today = self.get_transactions_today()
            context["transactions_today"] = transactions_today
            context["today_sales"] = self.get_today_sales()
            context["total_sales"] = self.get_total_sales()
            context["transactions"] = self.get_transactions().exclude(id__in=transactions_today)
        elif exists and not active:
            context["title"] = "Please contact Site Admin."
            # !!!!!!!!!!!!!!

        elif not exists and not active:
            context["title"] = "Apply for Account"
            context["apply_form"] = apply_form
        else:
            pass

        return render(request, "sellers/dashboard.html", context )




    def form_valid(self, form):
        valid_data = super().form_valid(form)
        obj = SellerAccount.objects.create(user=self.request.user)
        return valid_data





    def get_transactions_today(self):
        today = datetime.date.today()
        today_min = datetime.datetime.combine(today, datetime.time.min)
        today_max = datetime.datetime.combine(today, datetime.time.max)
        today_min = today_min.replace(tzinfo=timezone('UTC'))
        today_max = today_max.replace(tzinfo=timezone('UTC'))

        return self.get_transactions().filter(timestamp__range=(today_min, today_max))





    def get_total_sales(self):
        transactions = self.get_transactions().aggregate(Sum("price"))
        total_sales = transactions["price__sum"]
        return total_sales




    def get_today_sales(self):
        transactions = self.get_transactions_today().aggregate(Sum("price"))
        total_sales = transactions["price__sum"]
        return total_sales




    def get_total_average_sales(self):
        transactions = self.get_transactions_today().aggregate(Avg("price"))
        total_sales = transactions["price__avg"]
        return total_sales




    def get_total_and_average_of_sales(self):
        transactions = self.get_transactions_today().aggregate(Sum("price"), Avg("price"))
        return transactions

templates/sellers/dashboard.html
{% extends "base.html" %}
{% block style %} {% endblock style %}
{% load get_thumbnail %}
{% load static from staticfiles %}
{% load staticfiles %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}


{%block title%}Dashboard{%endblock title%}


{%block content%}

<small></small>

<div style="margin-left:10%;">
<div class="row" style="margin-bottom: 15px;">
<h1>{{title}}</h1>
</div>







{% if apply_form %}
<div class="row" style="margin-bottom: 15px;">

<form method="POST" action='' >  {% csrf_token %}
<p>Rules of the marketplace:</p>
<ol>
	<li>Be kind </li>
	<li>Sell well </li>
	<li>Tell the truth</li>
</ol>
<p>{{ apply_form }} </p>

<input type="submit"/>
</form>






{% else %}
</div>
{% endif %}


<br/>


<div class="row" style="margin-bottom: 15px;">


{% if transactions  %}
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12  col" style="margin-bottom: 0px;">

	{% if today_sales is None %}
<p>Today's sales is 0 Peanuts </p>

	{% else %}

<p>Today's sales is {{today_sales}} Peanuts </p>

{% include "sellers/transaction_list.html" with transaction_list=transactions_today %}

	{% endif %}

	<br/>
	<hr/>

<p>Recent Transaction History
	(Total sales
	{% if total_sales is None %} 0
	{% else %} Peanuts {{total_sales | floatformat:'2'}}
	{% endif %} )</p>



{% include "sellers/transaction_list.html" with transaction_list=transactions %}


<br><p><a href="{% url 'sellers:transactions' %}">View all transactions</a></p>

</div>


{% else %}
You are welcome!
{% endif %}




</div>
</div>



{% endblock content %}

templates/sellers/product_list_view.html
{% extends "base.html" %}
{% block style %}
{% endblock style %}
{% load get_thumbnail %}
{% load static from staticfiles %}
{% load staticfiles %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
{% load inclusion_tags %}


{%block title%}Offer{%endblock title%}


{%block content%}



<!-- <small>Items put on sale </small> -->

{% if user.is_authenticated %}
{% if user.is_staff %}
<div class="btn btn-secondary btn-sm">
	<a style="text-decoration: none;" href={% url 'sellers:product_create' %}>Add product</a></div>
{% endif %}
{% endif %}



<div class="row" style="margin-bottom: 15px;">
	<div class="col-xs-12 col-sm-6 col-md-6 col-lg-3  col1" style="margin-bottom: 30px;">
<h1>Items</h1>
	</div>
	<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6  col1" style="margin-bottom: 30px;">

	</div>
</div>

{%  include 'search.html' %}




<div class="row" style="margin-bottom: 10px; ">

{% include "products/product_list_snippet.html" with object_list=object_list %}

</div>







{% endblock content %} 

templates/sellers/transaction_list.html
<style>
.contents:hover {
	font-weight: 600;
}

.linen {
background-color: linen;

}
.gains {
background-color: gainsboro;
}


/*
.o {
background-color: linen;
}
.to {
background-color: gainsboro;
}
.tr {
background-color: linen;
}
.thr {
background-color: gainsboro;
}
.fv {
background-color: linen;
}
*/

</style>

<div class="row header contents gains" style="border-bottom: solid gainsboro 1px;">


<div id="prod-header" class="col-xs-3 col-sm-3 col-md-3 col-lg-3  product col-w o" style="margin-bottom: 0px; border: solid gray 0.5px;" title="Product" >
Item
</div>

<div id="buyer-header" class="col-xs-2 col-sm-2 col-md-2 col-lg-2  buyer col-w to" style="margin-bottom: 0px; border: solid gray 0.5px;" title="Buyer" >
Buyer
</div>


<div id="seller-header" class="col-xs-2 col-sm-2 col-md-2 col-lg-2  seller col-w tr" style="margin-bottom: 0px; border: solid gray 0.5px;" title="Seller">Seller</div>


<div id="price-header" class="col-xs-1 col-sm-1 col-md-1 col-lg-1  sale_total col-w thr" style="margin-bottom: 0px; border: solid gray 0.5px;"  title="Price">
Sale</div>



<div id="date-header"  class="col-xs-4 col-sm-4 col-md-4 col-lg-4  date_time col-w fv" style="margin-bottom: 0px; border: solid gray 0.5px;" title="Date">Date</div>
</div>  <!-- end row -->





	{% for trans in transaction_list %}



<div id='pokrowiec' class="{% cycle 'linen' 'gains' as rowcolor %}">


<div class="row contents rowcolor" style="border-bottom: solid gainsboro 1px; ">


<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3  product-c  col-w o" style="margin-bottom: 0px; border: solid gray 0.5px;" title="Product"><a href="{{trans.product.get_absolute_url}}" >
	{{trans.product}}</a></div>

<div class="col-xs-2 col-sm-2 col-md-2 col-lg-2  buyer-c col-w to" style="margin-bottom: 0px; border: solid gray 0.5px;">
<a href="{% url 'products:vendor_detail' trans.user %}" title="Buyer">{{trans.user.username}}</a></div>

<div class="col-xs-2 col-sm-2 col-md-2 col-lg-2  seller col-w tr" style="margin-bottom: 0px; border: solid gray 0.5px;"> <a href="{% url 'products:vendor_detail' trans.product.seller %}" title="Seller">{{trans.product.seller}}</a></div>

<div class="col-xs-1 col-sm-1 col-md-1 col-lg-1  sale_total-c col-w thr" style="margin-bottom: 0px; border: solid gray 0.5px;" title="Price">{{trans.price}}</div>

<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4  date_time-c col-w fv"  style="margin-bottom: 0px; border: solid gray 0.5px; " title="Date">{{trans.timestamp}}</div>



</div>  <!-- end row content1-->

</div>


{% endfor %}

templates/sellers/transaction_list_view.html
{% extends "base.html" %}
{% block title %}My sales{% endblock title %}
{% block style %}
{% endblock style %}
{% load get_thumbnail %}
{% load static from staticfiles %}
{% load staticfiles %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
{% load inclusion_tags %}


{%block content%}
<small>Recent Transactions</small>


<div class="row" style="margin-bottom: 10px; ">

<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6  col2" style="margin-bottom: 10px; ">
<h1>Transactions</h1>
</div>
<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6  col2" style="margin-bottom: 10px; ">

</div>
</div>






<div class="row">
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12  col2" style="margin-bottom: 10px;  white-space: normal;">


{% if object_list %}

{% include "sellers/transaction_list.html" with transaction_list=object_list %}

{% else %}
Please try later.
{% endif %}
</div>


</div>


{% endblock content %}